### ISSUE TITLE
Unhandled Exception: MissingPluginException

### ISSUE THREAD

**Issue by McCrafterIV** [mofada/flutter_update_app#5]
I got the following error while using the plugin:
```
E/flutter ( 8497): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method updateApp on channel cn.mofada.cn/update_app)
E/flutter ( 8497): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter ( 8497): <asynchronous suspension>
E/flutter ( 8497): #1      UpdateApp.updateApp (package:update_app/update_app.dart:17:33)
E/flutter ( 8497): #2      MyHomePage._install (package:appselfupdatetest/main.dart:46:17)
E/flutter ( 8497): <asynchronous suspension>
E/flutter ( 8497): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter ( 8497): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter ( 8497): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 8497): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter ( 8497): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter ( 8497): #8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
E/flutter ( 8497): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
E/flutter ( 8497): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter ( 8497): #11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter ( 8497): #12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter ( 8497): #13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter ( 8497): #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter ( 8497): #15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter ( 8497): #16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 8497): #17     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 8497): #18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 8497): #19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 8497): #20     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter ( 8497): #21     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 8497): #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter ( 8497): #23     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter ( 8497): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter ( 8497): 
```

I've used the same code as it is in the example:
```dart
UpdateApp.updateApp(url: filePath, appleId:"375380948",title:"Title",description:"Description");
```
I get the `filePath` from the FilePicker dependency and also checked the path. How do I resolve this issue? At this point, the plugin isn't usable at all because it crashes instantly.

**Comment by mofada** [comment]
Hello, please provide `flutter doctor -v`, I will take a look, thank you

**Comment by McCrafterIV** [comment]
Of course
```
>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.900], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at P:\XXX
    • Framework revision 0b8abb4724 (4 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at P:\XXX
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-R, build-tools 29.0.0
    • ANDROID_HOME = P:\XXX
    • Java binary at: P:\XXXX\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[!] Android Studio (version 4.0)
    • Android Studio at P:\XXX
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by mofada** [comment]
I'm very sorry, but I'm in a hurry for things that I'm busy working on lately. I may have to make changes later.

**Comment by McCrafterIV** [comment]
Ok, what does later mean? I mean, do I have to wait only a week or a month or so? If it would take to long I need to use an other dependency.. :/

**Comment by mofada** [comment]
My God, I have the same problem, I will update and publish it as soon as possible

**Comment by mofada** [comment]
You can use it first, I will test the ios part today and then post it, good night.
```
dependencies:
  #  update_app: ^0.1.3
  update_app:
    git:
      url: https://github.com/mofada/flutter_update_app.git
```

**Comment by McCrafterIV** [comment]
I've tested it. No error is thrown but also nothing is happening at all. After the APK file was selected I try to update using the following syntax:
```dart
await UpdateApp.updateApp(url: filePath, appleId:"375380948",title:"Title",description:"Description");
```
but it doesn't work. Flutter doctor also doesn't output something suspicious.

**Comment by mofada** [comment]
I use DownloadManager to download, you look at your notification bar, is there a download progress

![screen](https://user-images.githubusercontent.com/22286246/85196222-4a40e300-b30b-11ea-976b-5d1fd4d9a9d9.png)

**Comment by McCrafterIV** [comment]
My bad, 
I thought I have to provide a local path. After changing the path to a download URL it now works perfectly fine
Thanks for the help, I'll close this now

**Comment by mofada** [comment]
The plugin has been updated
```
dependencies:
  update_app: ^0.1.5
```
